name: code
on:
  push:
    branches:
      - master
jobs:
  build-code-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build code image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ehco1996/aioshadowsocks
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,code"
          tag_names: true
          dockerfile: Dockerfile.code
