name: runtime
on:
  push:
    branches:
      - build
jobs:
  build-runtime-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build-runtime-image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ehco1996/aioshadowsocks
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "runtime"
          dockerfile: Dockerfile
